package core;

public enum FractalType
{
	MANDELBROT_STANDARD,
	MANDELBROT_LEAF,
	MANDELBROT_CACTUS,
	MANDELBROT_MOONFISH,
	MANDELBROT_MILL,
	MANDELBROT_ARROWS,
	MANDELBROT_BALL,
	MANDELBROT_STAR,
	MANDELBROT_LEAF2,
	MANDELBROT_DAISY,
	MANDELBROT_FLAKE,
	MANDELBROT_FLAKE2,
	MANDELBROT_LEAF3,
	MANDELBROT_LEAF4,
	MANDELBROT_LEAF5,
	MANDELBROT_LEAF6,
	MANDELBROT_LEAF7,
	KOCH_SNOWFLAKE;
	
	public static FractalType[] getValues = values(); 
}